// app/layout.js
import { Geist, Geist_Mono, Anuphan } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anuphan = Anuphan({
  subsets: ['thai', 'latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-anuphan',
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // ต้องมีแท็ก html และ body ครอบเสมอ พร้อมผูกตัวแปรฟอนต์
    <html
      lang="th"
      className={`${geistSans.variable} ${geistMono.variable} ${anuphan.variable} h-full antialiased`}
    >
      {/* ใส่คลาส font-sans เพื่อเปลี่ยนฟอนต์เริ่มต้นของทั้งระบบตามที่ตั้งค่าใน Tailwind */}
      <body className="min-h-full flex flex-col font-sans">
        {children}
      </body>
    </html>
  );
}
